// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.vaadin.kanban.domain;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import org.vaadin.kanban.domain.StateColumnDataOnDemand;

privileged aspect StateColumnIntegrationTest_Roo_IntegrationTest {
    
    declare @type: StateColumnIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: StateColumnIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: StateColumnIntegrationTest: @Transactional;
    
    @Autowired
    private StateColumnDataOnDemand StateColumnIntegrationTest.dod;
    
    @Test
    public void StateColumnIntegrationTest.testCountStateColumns() {
        org.junit.Assert.assertNotNull("Data on demand for 'StateColumn' failed to initialize correctly", dod.getRandomStateColumn());
        long count = org.vaadin.kanban.domain.StateColumn.countStateColumns();
        org.junit.Assert.assertTrue("Counter for 'StateColumn' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void StateColumnIntegrationTest.testFindStateColumn() {
        org.vaadin.kanban.domain.StateColumn obj = dod.getRandomStateColumn();
        org.junit.Assert.assertNotNull("Data on demand for 'StateColumn' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'StateColumn' failed to provide an identifier", id);
        obj = org.vaadin.kanban.domain.StateColumn.findStateColumn(id);
        org.junit.Assert.assertNotNull("Find method for 'StateColumn' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'StateColumn' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void StateColumnIntegrationTest.testFindAllStateColumns() {
        org.junit.Assert.assertNotNull("Data on demand for 'StateColumn' failed to initialize correctly", dod.getRandomStateColumn());
        long count = org.vaadin.kanban.domain.StateColumn.countStateColumns();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'StateColumn', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.vaadin.kanban.domain.StateColumn> result = org.vaadin.kanban.domain.StateColumn.findAllStateColumns();
        org.junit.Assert.assertNotNull("Find all method for 'StateColumn' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'StateColumn' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void StateColumnIntegrationTest.testFindStateColumnEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'StateColumn' failed to initialize correctly", dod.getRandomStateColumn());
        long count = org.vaadin.kanban.domain.StateColumn.countStateColumns();
        if (count > 20) count = 20;
        java.util.List<org.vaadin.kanban.domain.StateColumn> result = org.vaadin.kanban.domain.StateColumn.findStateColumnEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'StateColumn' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'StateColumn' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void StateColumnIntegrationTest.testFlush() {
        org.vaadin.kanban.domain.StateColumn obj = dod.getRandomStateColumn();
        org.junit.Assert.assertNotNull("Data on demand for 'StateColumn' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'StateColumn' failed to provide an identifier", id);
        obj = org.vaadin.kanban.domain.StateColumn.findStateColumn(id);
        org.junit.Assert.assertNotNull("Find method for 'StateColumn' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyStateColumn(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'StateColumn' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void StateColumnIntegrationTest.testMerge() {
        org.vaadin.kanban.domain.StateColumn obj = dod.getRandomStateColumn();
        org.junit.Assert.assertNotNull("Data on demand for 'StateColumn' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'StateColumn' failed to provide an identifier", id);
        obj = org.vaadin.kanban.domain.StateColumn.findStateColumn(id);
        boolean modified =  dod.modifyStateColumn(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.vaadin.kanban.domain.StateColumn merged = (org.vaadin.kanban.domain.StateColumn) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'StateColumn' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void StateColumnIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'StateColumn' failed to initialize correctly", dod.getRandomStateColumn());
        org.vaadin.kanban.domain.StateColumn obj = dod.getNewTransientStateColumn(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'StateColumn' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'StateColumn' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'StateColumn' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void StateColumnIntegrationTest.testRemove() {
        org.vaadin.kanban.domain.StateColumn obj = dod.getRandomStateColumn();
        org.junit.Assert.assertNotNull("Data on demand for 'StateColumn' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'StateColumn' failed to provide an identifier", id);
        obj = org.vaadin.kanban.domain.StateColumn.findStateColumn(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'StateColumn' with identifier '" + id + "'", org.vaadin.kanban.domain.StateColumn.findStateColumn(id));
    }
    
}
