package org.vaadin.kanban.web;

import java.util.List;

import org.vaadin.kanban.domain.Card;
import org.vaadin.kanban.domain.StateColumn;
import org.vaadin.navigator.Navigator;

import com.vaadin.Application;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;

public class KanbanBoard extends CustomComponent implements Navigator.View {

    private AbsoluteLayout mainLayout;
    private GridLayout grid;

    /**
     * The constructor should first build the main layout, set the composition
     * root and then do any custom initialization.
     * 
     * The constructor will not be automatically regenerated by the visual
     * editor.
     */
    public KanbanBoard() {
        buildMainLayout();
        setCompositionRoot(mainLayout);

    }

    private AbsoluteLayout buildMainLayout() {
        mainLayout = new AbsoluteLayout();
        setWidth("100.0%");
        setHeight("100.0%");

        grid = new GridLayout();
        grid.setStyleName("board");
        grid.setSizeFull();
        grid.setImmediate(true);
        grid.setMargin(true);
        grid.setSpacing(true);
        mainLayout.addComponent(grid, "top:0.0px;left:0.0px;");

        return mainLayout;
    }

    @Override
    public void init(Navigator navigator, Application application) {
        // nothing to do
    }

    @Override
    public void navigateTo(String requestedDataId) {
        List<StateColumn> columns = StateColumn.findAllStateColumns();

        grid.removeAllComponents();
        if (columns.size() < 1) {
            return;
        }
        grid.setColumns(columns.size());
        grid.setRows(3);
        grid.setRowExpandRatio(0, 0);
        grid.setRowExpandRatio(1, 2);
        grid.setRowExpandRatio(2, 0);
        for (StateColumn stateColumn : columns) {
            int sortOrder = stateColumn.getSortOrder();

            VerticalLayout header = new VerticalLayout();
            header.setSizeUndefined();
            header.setWidth(100, UNITS_PERCENTAGE);

            Label name = new Label("<h2>" + stateColumn.getName() + "</h2>",
                    Label.CONTENT_XHTML);
            name.setStyleName("header");
            name.setSizeUndefined();
            name.setWidth(100, UNITS_PERCENTAGE);
            header.addComponent(name);

            Label wip = new Label("" + stateColumn.getWorkInProgressLimit(),
                    Label.CONTENT_XHTML);
            wip.setStyleName("wip");
            wip.setSizeUndefined();
            wip.setWidth(100, UNITS_PERCENTAGE);
            header.addComponent(wip);

            grid.addComponent(header, sortOrder, 0);

            KanbanColumn column = new KanbanColumn(stateColumn);
            grid.addComponent(column, sortOrder, 1);
            for (Card card : Card.findCardsByStateColumn(stateColumn)
                    .getResultList()) {
                column.addComponent(new KanbanCard(card));
            }

            Label dod = new Label("<b>Definition of done</b>"
                    + stateColumn.getDefinitionOfDone(), Label.CONTENT_XHTML);
            dod.setStyleName("dod");
            dod.setSizeUndefined();
            grid.addComponent(dod, sortOrder, 2);
        }
    }

    @Override
    public String getWarningForNavigatingFrom() {
        return null;
    }
}
