// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.vaadin.kanban.domain;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import org.vaadin.kanban.domain.CardDataOnDemand;

privileged aspect CardIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CardIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CardIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: CardIntegrationTest: @Transactional;
    
    @Autowired
    private CardDataOnDemand CardIntegrationTest.dod;
    
    @Test
    public void CardIntegrationTest.testCountCards() {
        org.junit.Assert.assertNotNull("Data on demand for 'Card' failed to initialize correctly", dod.getRandomCard());
        long count = org.vaadin.kanban.domain.Card.countCards();
        org.junit.Assert.assertTrue("Counter for 'Card' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CardIntegrationTest.testFindCard() {
        org.vaadin.kanban.domain.Card obj = dod.getRandomCard();
        org.junit.Assert.assertNotNull("Data on demand for 'Card' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Card' failed to provide an identifier", id);
        obj = org.vaadin.kanban.domain.Card.findCard(id);
        org.junit.Assert.assertNotNull("Find method for 'Card' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Card' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CardIntegrationTest.testFindAllCards() {
        org.junit.Assert.assertNotNull("Data on demand for 'Card' failed to initialize correctly", dod.getRandomCard());
        long count = org.vaadin.kanban.domain.Card.countCards();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Card', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.vaadin.kanban.domain.Card> result = org.vaadin.kanban.domain.Card.findAllCards();
        org.junit.Assert.assertNotNull("Find all method for 'Card' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Card' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CardIntegrationTest.testFindCardEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Card' failed to initialize correctly", dod.getRandomCard());
        long count = org.vaadin.kanban.domain.Card.countCards();
        if (count > 20) count = 20;
        java.util.List<org.vaadin.kanban.domain.Card> result = org.vaadin.kanban.domain.Card.findCardEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Card' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Card' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CardIntegrationTest.testFlush() {
        org.vaadin.kanban.domain.Card obj = dod.getRandomCard();
        org.junit.Assert.assertNotNull("Data on demand for 'Card' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Card' failed to provide an identifier", id);
        obj = org.vaadin.kanban.domain.Card.findCard(id);
        org.junit.Assert.assertNotNull("Find method for 'Card' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCard(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Card' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CardIntegrationTest.testMerge() {
        org.vaadin.kanban.domain.Card obj = dod.getRandomCard();
        org.junit.Assert.assertNotNull("Data on demand for 'Card' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Card' failed to provide an identifier", id);
        obj = org.vaadin.kanban.domain.Card.findCard(id);
        boolean modified =  dod.modifyCard(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.vaadin.kanban.domain.Card merged = (org.vaadin.kanban.domain.Card) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Card' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CardIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Card' failed to initialize correctly", dod.getRandomCard());
        org.vaadin.kanban.domain.Card obj = dod.getNewTransientCard(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Card' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Card' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Card' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CardIntegrationTest.testRemove() {
        org.vaadin.kanban.domain.Card obj = dod.getRandomCard();
        org.junit.Assert.assertNotNull("Data on demand for 'Card' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Card' failed to provide an identifier", id);
        obj = org.vaadin.kanban.domain.Card.findCard(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Card' with identifier '" + id + "'", org.vaadin.kanban.domain.Card.findCard(id));
    }
    
}
